views/backend.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# Copyright (c) 2015 Steffen Deusch
# Licensed under the MIT license
# MonitorNjus, 28.11.2015 (Version 1.1)
# Backend View

from flask import render_template, request, Blueprint
from modules.code import common
import settings
from tools import requires_auth, ssl_required

backend = Blueprint('backend', __name__, template_folder='templates')

adminnav = [('../admin/', "Haupteinstellungen"),
            ('../admin/widgets', "Widgets"), ('../', "Frontend")]


@backend.route('/admin/')
@ssl_required
@requires_auth
def admin_index():
    reload(common)
    from modules.code import colors
    reload(colors)
    return render_template('backend/index.html', common=common, settings=settings, colors=colors, navigation=adminnav)


@backend.route('/admin/widgets')
@ssl_required
@requires_auth
def admin_widgets():
    reload(common)
    from modules.code import colors
    reload(colors)
    return render_template('backend/widgets.html', common=common, colors=colors, navigation=adminnav)


@backend.route('/admin/setn', methods=["GET", "POST"])
@ssl_required
@requires_auth
def admin_setn():
    from modules.backend import setn

    form1 = request.form
    form2 = request.args
    form = {}
    for item in form1:
        form[item] = form1[item]
    for item in form2:
        form[item] = form2[item]

    refresh = setn.setn(form)
    return render_template('backend/setn.html', refresh=refresh)

templates/backend/base.html
<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	<link href="{{ url_for('static', filename='css/materialize.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
	<title>{% block title %}MonitorNjus Admin-Panel{% endblock %}</title>
	<!-- MonitorNjus -->
	<!-- Copyright (c) {{ common.datum.year }} Steffen Deusch -->
	<!-- https://github.com/SteffenDE/MonitorNjus -->
	{{ colors.adminstyles|safe }}
</head>
<body>
	<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
	<nav class="{{ colors.color }} navigation">
		<div class="container">
			<div class="nav-wrapper">
				<a id="logo-container" href="../admin/" class="brand-logo">MonitorNjus Admin-Panel</a>
				<a href="#" data-activates="mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
				{% for item in range(0,2) %}
				{% if item == 0 %}
				<ul id="nav-mobile" class="right hide-on-med-and-down">
				{% else %}
				<ul class="side-nav" id="mobile">
				{% endif %}
				{% for href, name in navigation %}
					<li {{ 'class="active"'|safe if sitename in name.lower() }}><a href="{{ href }}">{{ name }}</a></li>
				{% endfor %}
				</ul>
				{% endfor %}
			</div>
		</div>
	</nav>
	{% block content %}{% endblock %}
	{% block footer %}
	<footer class="page-footer {{ colors.color }}">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text">MonitorNjus für das JVG-Ehingen</h5>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				&copy; Steffen Deusch {{ common.datum.year }}
				<a class="grey-text text-lighten-4 right" href="https://github.com/SteffenDE/monitornjus">{{ common.version|safe }}</a>
			</div>
		</div>
	</footer>
	<!-- Scripts -->
	<script type="text/javascript" src="{{ url_for('static', filename='js/init.js') }}"></script>
	{% endblock %}
</body>
</html>

templates/backend/index.html
{% extends 'backend/base.html' %}
{% set sitename = 'haupteinstellungen' %}
{% set rows = common.getrows() %}
{% set rowsone = rows + 1 %}
{% block content %}
	<h3 class="header center {{ colors.color }}-text">Haupteinstellungen</h3>
	<div class="container">
		<div class="row">
			<form class="col s12" action="{{ url_for('backend.admin_setn') }}" method="post">
				<input type="hidden" name="referer" value="index" />
				<div class="row">
		{% for item in range(0,rows+1) %}
			{% if item in common.getallrows() %}
					<div class="col s12">
						<h5 class="header center {{ colors.color }}-text">Displayset {{ item }}</h5>
						<div class="row">
							<div class="col s6">
								<div class="card white darken-1">
									<div class="card-content white-text">
										<span class="card-title {{ colors.color }}-text text-darken-2">Linke Seite</span><br>
										<div class="row">
											<div class="input-field col s6">
												<input value="{{ common.testexist("URL", "Links", item) }}" name="URL-Links-{{ item }}" id="URL-Links-{{ item }}" type="text">
												<label for="URL-Links-{{ item }}">URL Links</label>
											</div>
											<div class="input-field col s6">
												<input value="{{ common.testexist("REFRESH", "Links", item) }}" name="REFRESH-Links-{{ item }}" id="REFRESH-Links-{{ item }}" type="number">
												<label for="REFRESH-Links-{{ item }}">Refresh Links</label>
											</div>
										</div>
										<div>
											<input type="checkbox" name="AKTIV-Links-{{ item }}" id="AKTIV-Links-{{ item }}" {{ common.aktiv("AKTIV", "Links", item)|safe }}/>
											<label for="AKTIV-Links-{{ item }}">Links aktiviert</label>&nbsp;&nbsp;&nbsp;&nbsp;
											<input type="hidden" value="0" name="HIDDEN.AKTIV-Links-{{ item }}">
											<input type="checkbox" name="REFRESHAKTIV-Links-{{ item }}" id="REFRESHAKTIV-Links-{{ item }}" {{ common.aktiv("REFRESHAKTIV", "Links", item)|safe }}/>
											<label for="REFRESHAKTIV-Links-{{ item }}">Links neu laden</label>
											<input type="hidden" value="0" name="HIDDEN.REFRESHAKTIV-Links-{{ item }}">
										</div>
										<div class="row">
											<div class="input-field col s4">
												<input value="{{ common.getdate("uhrzeit", "Links", item) }}" name="uhrzeit-Links-{{ item }}" id="uhrzeit-Links-{{ item }}" type="text">
												<label for="uhrzeit-Links-{{ item }}">Uhrzeit</label>
											</div>
											<div class="input-field col s4">
												<input value="{{ common.getdate("wochentag", "Links", item) }}" name="wochentag-Links-{{ item }}" id="wochentag-Links-{{ item }}" type="text">
												<label for="wochentag-Links-{{ item }}">Wochentag</label>
											</div>
											<div class="input-field col s2">
												<input value="{{ common.getdate("tag", "Links", item) }}" name="tag-Links-{{ item }}" id="tag-Links-{{ item }}" type="text">
												<label for="tag-Links-{{ item }}">Tag</label>
											</div>
											<div class="input-field col s2">
												<input value="{{ common.getdate("monat", "Links", item) }}" name="monat-Links-{{ item }}" id="monat-Links-{{ item }}" type="text">
												<label for="monat-Links-{{ item }}">Monat</label>
											</div>
										</div>
										<div class="row">
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINLEFT","Links", item) }}" name="MARGINLEFT-Links-{{ item }}" id="MARGINLEFT-Links-{{ item }}" type="text">
												<label for="MARGINLEFT-Links-{{ item }}">Rand-Links</label>
											</div>
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINRIGHT","Links", item) }}" name="MARGINRIGHT-Links-{{ item }}" id="MARGINRIGHT-Links-{{ item }}" type="text">
												<label for="MARGINRIGHT-Links-{{ item }}">Rand-Rechts</label>
											</div>
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINTOP","Links", item) }}" name="MARGINTOP-Links-{{ item }}" id="MARGINTOP-Links-{{ item }}" type="text">
												<label for="MARGINTOP-Links-{{ item }}">Rand-Oben</label>
											</div>
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINBOTTOM","Links", item) }}" name="MARGINBOTTOM-Links-{{ item }}" id="MARGINBOTTOM-Links-{{ item }}" type="text">
												<label for="MARGINBOTTOM-Links-{{ item }}">Rand-Unten</label>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col s6">
								<div class="card white darken-1">
									<div class="card-content white-text">
										<span class="card-title {{ colors.color }}-text text-darken-2">Rechte Seite</span><br>
										<div class="row">
											<div class="input-field col s6">
												<input value="{{ common.testexist("URL", "Rechts", item) }}" name="URL-Rechts-{{ item }}" id="URL-Rechts-{{ item }}" type="text">
												<label for="URL-Rechts-{{ item }}">URL Rechts</label>
											</div>
											<div class="input-field col s6">
												<input value="{{ common.testexist("REFRESH", "Rechts", item) }}" name="REFRESH-Rechts-{{ item }}" id="REFRESH-Rechts-{{ item }}" type="number">
												<label for="REFRESH-Rechts-{{ item }}">Refresh Rechts</label>
											</div>
										</div>
										<div>
											<input type="checkbox" name="AKTIV-Rechts-{{ item }}" id="AKTIV-Rechts-{{ item }}" {{ common.aktiv("AKTIV", "Rechts", item)|safe }}/>
											<label for="AKTIV-Rechts-{{ item }}">Rechts aktiviert</label>&nbsp;&nbsp;&nbsp;&nbsp;
											<input type="hidden" value="0" name="HIDDEN.AKTIV-Rechts-{{ item }}">
											<input type="checkbox" name="REFRESHAKTIV-Rechts-{{ item }}" id="REFRESHAKTIV-Rechts-{{ item }}" {{ common.aktiv("REFRESHAKTIV", "Rechts", item)|safe }}/>
											<label for="REFRESHAKTIV-Rechts-{{ item }}">Rechts neu laden</label>
											<input type="hidden" value="0" name="HIDDEN.REFRESHAKTIV-Rechts-{{ item }}">
										</div>
										<div class="row">
											<div class="input-field col s4">
												<input value="{{ common.getdate("uhrzeit", "Rechts", item) }}" name="uhrzeit-Rechts-{{ item }}" id="uhrzeit-Rechts-{{ item }}" type="text">
												<label for="uhrzeit-Rechts-{{ item }}">Uhrzeit</label>
											</div>
											<div class="input-field col s4">
												<input value="{{ common.getdate("wochentag", "Rechts", item) }}" name="wochentag-Rechts-{{ item }}" id="wochentag-Rechts-{{ item }}" type="text">
												<label for="wochentag-Rechts-{{ item }}">Wochentag</label>
											</div>
											<div class="input-field col s2">
												<input value="{{ common.getdate("tag", "Rechts", item) }}" name="tag-Rechts-{{ item }}" id="tag-Rechts-{{ item }}" type="text">
												<label for="tag-Rechts-{{ item }}">Tag</label>
											</div>
											<div class="input-field col s2">
												<input value="{{ common.getdate("monat", "Rechts", item) }}" name="monat-Rechts-{{ item }}" id="monat-Rechts-{{ item }}" type="text">
												<label for="monat-Rechts-{{ item }}">Monat</label>
											</div>
										</div>
										<div class="row">
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINLEFT","Rechts", item) }}" name="MARGINLEFT-Rechts-{{ item }}" id="MARGINLEFT-Rechts-{{ item }}" type="text">
												<label for="MARGINLEFT-Rechts-{{ item }}">Rand-Links</label>
											</div>
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINRIGHT","Rechts", item) }}" name="MARGINRIGHT-Rechts-{{ item }}" id="MARGINRIGHT-Rechts-{{ item }}" type="text">
												<label for="MARGINRIGHT-Rechts-{{ item }}">Rand-Rechts</label>
											</div>
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINTOP","Rechts", item) }}" name="MARGINTOP-Rechts-{{ item }}" id="MARGINTOP-Rechts-{{ item }}" type="text">
												<label for="MARGINTOP-Rechts-{{ item }}">Rand-Oben</label>
											</div>
											<div class="input-field col s3">
												<input value="{{ common.getinfo("MARGINBOTTOM","Rechts", item) }}" name="MARGINBOTTOM-Rechts-{{ item }}" id="MARGINBOTTOM-Rechts-{{ item }}" type="text">
												<label for="MARGINBOTTOM-Rechts-{{ item }}">Rand-Unten</label>
											</div>
										</div>
									</div>
								</div>
							</div>
				{% if rows != 1 %}
						<center><a class="waves-effect waves-light btn" href="setn?referer=row&delnum={{ item }}">Displayset l&ouml;schen</a></center>
				{% endif %}
						</div>
					</div>
			{% endif %}
		{% endfor %}
					<div class="col s12">
						<center><a class="btn waves-effect waves-light {{ colors.color }}" href=setn?referer=row&createnum={{ rowsone }}><i class="mdi-content-add"></i></a></center>
						<p class="range-field"><input type="range" id="teilung" name="teilung" min="1" max="99" value="{{ common.readsettings("TEILUNG") }}" /></p>
						<div class="row">
							<div class="col s6">
								<div class="card white darken-1">
									<div class="card-content white-text">
										<span class="card-title {{ colors.color }}-text text-darken-2">Alle Seiten</span><br>
										<div class="row">
											<div class="input-field col s12">
												<input value="{{ common.testexist("REFRESH", "global", 0) }}" name="REFRESH-global-0" id="REFRESH-global-0" type="text">
												<label for="REFRESH-global-0">Alle Seiten neu laden</label>
											</div>
										</div>
										<div>
											<input type="checkbox" name="REFRESHAKTIV-global-0" id="REFRESHAKTIV-global-0" {{ common.aktiv("REFRESHAKTIV", "global", 0)|safe }}/>
											<label for="REFRESHAKTIV-global-0">Globales neu laden aktiviert</label>
											<input type="hidden" value="0" name="HIDDEN.REFRESHAKTIV-global-0">
										</div>
									</div>
								</div>
							</div>
							<div class="col s6">
								<div class="card white darken-1">
									<div class="card-content white-text">
										<span class="card-title {{ colors.color }}-text text-darken-2">Monitornjus Frontend</span><br>
										<div class="row">
											<div class="input-field col s12">
												<input value="{{ common.testexist("REFRESH", "globalmon", 0) }}" name="REFRESH-globalmon-0" id="REFRESH-globalmon-0" type="text">
												<label for="REFRESH-globalmon-0">Monitornjus Frontend neu laden</label>
											</div>
										</div>
										<div>
											<input type="checkbox" name="REFRESHAKTIV-globalmon-0" id="REFRESHAKTIV-globalmon-0" {{ common.aktiv("REFRESHAKTIV", "globalmon", 0)|safe }}/>
											<label for="REFRESHAKTIV-globalmon-0">Monitornjus neu laden</label>
											<input type="hidden" value="0" name="HIDDEN.REFRESHAKTIV-globalmon-0">
										</div>
									</div>
								</div>
							</div>
						</div>
						<button class="btn waves-effect waves-light" type="submit">Abschicken<i class="mdi-content-send right"></i></button>
	{% if settings.triggerrefresh %}
						<a class="waves-effect waves-light btn right" href="setn?referer=triggerrefresh">Neuladen auslösen</a>
	{% endif %}
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

templates/backend/setn.html
<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="refresh" content="0; URL={{ refresh }}">
</head>
</html>

templates/backend/widgets.html
{% extends 'backend/base.html' %}
{% set sitename = 'widgets' %}
{% block content %}
	<h3 class="header center {{ colors.color }}-text">Widgets</h3>
	<div class="container">
		<div class="row">
			<div class="col s6">
				<form class="col s12" action="{{ url_for('backend.admin_setn') }}" method="post">
					<input type="hidden" name="referer" value="widgets" />
					<ul class="collapsible" data-collapsible="accordion">
{% set count = common.getwidgets() %}
{% for item in count %}
	{% set typ = common.getwidgTYPfromID(item) %}
		{% if typ == "Adminlink" %}
						<li>
							<div class="collapsible-header active">{{ item }}. Admin-Link</div>
							<div class="collapsible-body">
								<div class="container" style="min-width: 100%; padding-top: 5%;">
									<input type="checkbox" name="AKTIV-Adminlink-{{ item }}" id="AKTIV-Adminlink-{{ item }}" {{ common.widgaktiv("Adminlink", item)|safe }}/>
									<label for="AKTIV-Adminlink-{{ item }}">Adminlink aktiviert</label>
									<input type="hidden" value="0" name="HIDDEN.AKTIV-Adminlink-{{ item }}">
									<div class="row">
										<div class="col s6">
											<select name="valign-Adminlink-{{ item }}">{{ common.valign("Adminlink", item, "valign")|safe }}
											</select>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Adminlink", item, "align") }}' name="align-Adminlink-{{ item }}" id="align-Adminlink-{{ item }}" type="text"/>
													<label for="align-Adminlink-{{ item }}">Vertikaler Abstand</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<select name="vmargin-Adminlink-{{ item }}">{{ common.valign("Adminlink", item, "vmargin")|safe }}
											</select>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Adminlink", item, "margin") }}' name="margin-Adminlink-{{ item }}" id="margin-Adminlink-{{ item }}" type="text"/>
													<label for="margin-Adminlink-{{ item }}">Horizontaler Abstand</label>
												</div>
											</div>
										</div>
									</div>
								</div>
		{% elif typ == "Logo" %}
						<li>
							<div class="collapsible-header">{{ item }}. Logo</div>
							<div class="collapsible-body">
								<div class="container" style="min-width: 100%; padding-top: 5%;">
									<input type="checkbox" name="AKTIV-Logo-{{ item }}" id="AKTIV-Logo-{{ item }}" {{ common.widgaktiv("Logo", item)|safe }}/>
									<label for="AKTIV-Logo-{{ item }}">Logo aktiviert</label>
									<input type="hidden" value="0" name="HIDDEN.AKTIV-Logo-{{ item }}">
									<div class="row">
										<div class="input-field col s12">
											<input value="{{ common.getwidgetinfo("Logo", item, "URL") }}" name="URL-Logo-{{ item }}" id="URL-Logo-{{ item }}" type="text"/>
											<label for="URL-Logo-{{ item }}">Logo-URL</label>
										</div>
									</div>
									<div class="row">
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Logo", item, "height") }}' name="height-Logo-{{ item }}" id="height-Logo-{{ item }}" type="text"/>
													<label for="height-Logo-{{ item }}">Logo-H&ouml;he</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Logo", item, "width") }}' name="width-Logo-{{ item }}" id="width-Logo-{{ item }}" type="text"/>
													<label for="width-Logo-{{ item }}">Logo-Breite</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<select name="valign-Logo-{{ item }}">{{ common.valign("Logo", item, "valign")|safe }}
											</select>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Logo", item, "align") }}' name="align-Logo-{{ item }}" id="align-Logo-{{ item }}" type="text"/>
													<label for="align-Logo-{{ item }}">Vertikaler Abstand</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<select name="vmargin-Logo-{{ item }}">{{ common.valign("Logo", item, "vmargin")|safe }}
											</select>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Logo", item, "margin") }}' name="margin-Logo-{{ item }}" id="margin-Logo-{{ item }}" type="text"/>
													<label for="margin-Logo-{{ item }}">Horizontaler Abstand</label>
												</div>
											</div>
										</div>
									</div>
								</div>
		{% elif typ == "Freies_Widget" %}
						<li>
							<div class="collapsible-header">{{ item }}. Freies Widget</div>
							<div class="collapsible-body">
								<div class="container" style="min-width: 100%; padding-top: 5%;">
									<input type="checkbox" name="AKTIV-Freies_Widget-{{ item }}" id="AKTIV-Freies_Widget-{{ item }}" {{ common.widgaktiv("Freies_Widget", item)|safe }}/>
									<label for="AKTIV-Freies_Widget-{{ item }}">Widget aktiviert</label>
									<input type="hidden" value="0" name="HIDDEN.AKTIV-Freies_Widget-{{ item }}">
									<div class="row">
										<div class="input-field col s12">
											<textarea style="color:black;" name="URL-Freies_Widget-{{ item }}" id="URL-Freies_Widget-{{ item }}" class="materialize-textarea">{{ common.getwidgetinfo("Freies_Widget", item, "URL") }}</textarea>
											<label for="URL-Freies_Widget-{{ item }}">Widget-URL</label>
										</div>
									</div>
									<div class="row">
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Freies_Widget", item, "height") }}' name="height-Freies_Widget-{{ item }}" id="height-Freies_Widget-{{ item }}" type="text"/>
													<label for="height-Freies_Widget-{{ item }}">Widget-H&ouml;he</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Freies_Widget", item, "width") }}' name="width-Freies_Widget-{{ item }}" id="width-Freies_Widget-{{ item }}" type="text"/>
													<label for="width-Freies_Widget-{{ item }}">Widget-Breite</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<select name="valign-Freies_Widget-{{ item }}">{{ common.valign("Freies_Widget", item, "valign")|safe }}
											</select>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Freies_Widget", item, "align") }}' name="align-Freies_Widget-{{ item }}" id="align-Freies_Widget-{{ item }}" type="text"/>
													<label for="align-Freies_Widget-{{ item }}">Vertikaler Abstand</label>
												</div>
											</div>
										</div>
										<div class="col s6">
											<select name="vmargin-Freies_Widget-{{ item }}">{{ common.valign("Freies_Widget", item, "vmargin")|safe }}
											</select>
										</div>
										<div class="col s6">
											<div class="row">
												<div class="input-field col s12">
													<input value='{{ common.getwidgetinfo("Freies_Widget", item, "margin") }}' name="margin-Freies_Widget-{{ item }}" id="margin-Freies_Widget-{{ item }}" type="text"/>
													<label for="margin-Freies_Widget-{{ item }}">Horizontaler Abstand</label>
												</div>
											</div>
										</div>
									</div>
								</div>
		{% endif %}
		{% if typ != "Adminlink" %}
								<center><a class="waves-effect waves-light btn" href="{{ url_for('backend.admin_setn') }}?referer=delwidget&delnum={{ item }}">Widget l&ouml;schen</a></center>
		{% endif %}
							</div>
						</li>
		{% endfor %}
					</ul>
					<button class="btn waves-effect waves-light" type="submit">Abschicken<i class="mdi-content-send right"></i></button>
				</form>
			</div>
			<div class="col s6">
				<form class="col s12" action="{{ url_for('backend.admin_setn') }}" method="post">
					<div class="card-panel">
						<div class="row">
							<input type="hidden" name="referer" value="newwidget" />
							<div class="input-field col s12">
								<select name="art">
									<option value="" disabled selected>Widgetart w&auml;hlen</option>
									<option value="Logo">Logo</option>
									<option value="Freies_Widget">Freies Widget</option>
								</select>
								<label>Materialize Select</label>
							</div>
						</div>
					</div>
					<button class="btn waves-effect waves-light" type="submit">Widget hinzuf&uuml;gen.</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}