views/backend.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# Copyright (c) 2015 Steffen Deusch
# Licensed under the MIT license
# MonitorNjus, 28.11.2015 (Version 1.1)
# Backend View

from flask import render_template, request, Blueprint
from modules.code import common
import settings
from tools import requires_auth, ssl_required

backend = Blueprint('backend', __name__, template_folder='templates')

adminnav = [('../admin/', "Haupteinstellungen"),
            ('../admin/widgets', "Widgets"), ('../', "Frontend")]


@backend.route('/admin/')
@ssl_required
@requires_auth
def admin_index():
    reload(common)
    from modules.code import colors
    reload(colors)
    return render_template('backend/index.html', common=common, settings=settings, colors=colors, navigation=adminnav)


@backend.route('/admin/widgets')
@ssl_required
@requires_auth
def admin_widgets():
    reload(common)
    from modules.code import colors
    reload(colors)
    return render_template('backend/widgets.html', common=common, colors=colors, navigation=adminnav)


@backend.route('/admin/setn', methods=["GET", "POST"])
@ssl_required
@requires_auth
def admin_setn():
    from modules.backend import setn

    form1 = request.form
    form2 = request.args
    form = {}
    for item in form1:
        form[item] = form1[item]
    for item in form2:
        form[item] = form2[item]

    refresh = setn.setn(form)
    return render_template('backend/setn.html', refresh=refresh)

views/frontend.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# Copyright (c) 2015 Steffen Deusch
# Licensed under the MIT license
# MonitorNjus, 28.11.2015 (Version 1.1)
# Frontend View

from flask import url_for, render_template, request, Response, flash, make_response, Blueprint
from modules.code import common
import settings
from tools import raise_helper

frontend = Blueprint('frontend', __name__, template_folder='templates')


@frontend.route('/')
def binindex():
    import datetime
    trigger = request.args.get("disabletrigger")
    owndate = request.args.get("owndate")
    return render_template('frontend/index.html', common=common, settings=settings, trigger=trigger, owndate=owndate)


@frontend.route('/show')
def binshow():
    from modules.frontend import show
    reload(show)
    owndate = request.args.get("owndate")
    geteilt, linksgeteilt, rechtsgeteilt, timeR, timeL, teilung = show.show(
        owndate)
    return render_template('frontend/show.html', common=common, geteilt=geteilt, linksgeteilt=linksgeteilt, rechtsgeteilt=rechtsgeteilt, timeR=timeR, timeL=timeL, teilung=teilung, raise_helper=raise_helper, owndate=owndate)


@frontend.route('/contentset')
def bin_contentset():
    from modules.frontend import contentset
    from modules.code import getytid
    owndate = request.args.get("owndate")
    gseite = request.args.get('seite', None)
    gnummer = request.args.get('nummer', None)
    nummer, nextnummer, refreshon, refresh, seite, mseite, typ, url = contentset.contentset(
        gseite, gnummer, owndate)
    return render_template('frontend/contentset.html', common=common, getytid=getytid, nummer=nummer, nextnummer=nextnummer, refreshon=refreshon, refresh=refresh, seite=seite, mseite=mseite, typ=typ, url=url, owndate=owndate)


@frontend.route('/triggerrefresh')
def triggerrefresh():
    if settings.triggerrefresh:
        import time

        def events():
            ttime = 0
            while True:
                try:
                    reload(common)
                    content = int(common.readsettings("REFRESH"))
                    if int(content) == 1:
                        yield "data: reload\n\n"
                        time.sleep(4)
                        common.writesettings("REFRESH", "0")
                        break
                    elif ttime >= 3600:
                        break
                    else:
                        yield "data: none\n\n"
                        time.sleep(3)
                    ttime += 3
                except:
                    break

        if settings.running_with_iis:
            reload(common)
            content = int(common.readsettings("REFRESH"))
            if int(content) == 1:
                out = "data: reload\n\n"
                time.sleep(4)
                common.writesettings("REFRESH", "0")
            else:
                out = "data: none\n\n"
            return Response(out, content_type="text/event-stream")

        else:
            return Response(events(), content_type='text/event-stream')
    else:
        return render_template('error/400.html'), 400

templates/frontend/contentset.html
<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8">
	{% if refreshon %}
	<meta http-equiv="refresh" content="{{ refresh }}; URL=contentset?seite={{ seite }}&nummer={{ nextnummer }}{{ '&owndate='|safe ~ owndate if owndate != None else '' }}">
	{% endif %}
	<title>MonitorNjus</title>
	<!-- MonitorNjus -->
	<!-- Copyright (c) {{ common.datum.year }} Steffen Deusch -->
	<!-- https://github.com/SteffenDE/MonitorNjus -->
	<style>
	{% if typ == 'video' %}
	.videocontainer 
	{
		position:absolute;
		height:100%;
		width:100%;
		overflow: hidden;
		top: 0px;
	}
	.videocontainer video 
	{
		min-width: 100%;
		min-height: 100%;
	}
	{% elif typ == 'image' %}
	#background {
		position: absolute;
		min-height:100%;
		width: 100%;
		height: auto;
		top: 0;
		left: 0;
		background: url({{ url }}) no-repeat center center;
		background-size: contain;         /* around images */
	{% endif %}
	iframe {
		padding-left: 0px;
		padding-right: 0px;
		padding-top: 0px;
		padding-bottom: 0px;
		box-sizing: border-box;
	}
	.fadeIn {
		opacity:0;
		-webkit-animation:fadeIn ease-in 1;
		-moz-animation:fadeIn ease-in 1;
		-o-animation:fadeIn ease-in 1;
		animation:fadeIn ease-in 1;
		-webkit-animation-fill-mode:forwards;
		-moz-animation-fill-mode:forwards;
		-o-animation-fill-mode:forwards;
		animation-fill-mode:forwards;
	}
	.fadeIn-animation {
		-webkit-animation-duration:0.8s;
		-moz-animation-duration:0.8s;
		-o-animation-duration:0.8s;
		animation-duration:0.8s;
	}
	@-webkit-keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
	@-moz-keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
	@-o-keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
	@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }

	{% if typ != ('image' or 'video') %}
	iframe {
		padding-left: {{ common.addpx(common.getinfo("MARGINLEFT", mseite, nummer)) }};
		padding-right: {{ common.addpx(common.getinfo("MARGINRIGHT", mseite, nummer)) }};
		padding-top: {{ common.addpx(common.getinfo("MARGINTOP", mseite, nummer)) }};
		padding-bottom: {{ common.addpx(common.getinfo("MARGINBOTTOM", mseite, nummer)) }};
		box-sizing: border-box;
	}
	{% endif %}
	</style>
</head>
<body class="fadeIn fadeIn-animation">
	{% if typ == 'image' %}
	<div id="background"></div>
	{% elif typ == 'video' %}
	<div class="videocontainer"><video src="{{ url }}" style="width:100%; height:auto; max-height: 100%;" autoplay="autoplay" loop="loop">Dein Browser unterst&uuml;tzt keine HTML5 Videos...</video></div>
	{% elif typ == 'pdf' %}
	<iframe src="{{ url }}" style="position:absolute; z-index:9; height:98%; width:98%; border-style:none; overflow:hidden" scrolling="no" frameborder="0"></iframe>
	{% elif typ == 'youtube' %}
	<iframe style="position:absolute; height:100%; width:100%; top:0px; left: 0px; border-style:none; overflow:hidden" scrolling="no" frameborder="0" src="//www.youtube.com/embed/{{ getytid.video_id(url) }}?rel=0&autoplay=1&loop=1&controls=0&showinfo=0"></iframe>
	{% else %}
	<iframe src="{{ url }}" style="position:absolute; width:100%; height:100%; top:0px; left:0px; border-style:none;" scrolling="no" frameborder="0"></iframe>
	{% endif %}
</body>
</html>

templates/frontend/index.html
<!DOCTYPE html>
<html style="overflow: hidden;" lang="de">
<head>
	<meta charset="UTF-8">
	<link href="{{ url_for('static', filename='css/mnews.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
	{% if common.getinfo("REFRESHAKTIV", "globalmon", 0)|int == 1 %}
	{{ '<meta http-equiv="refresh" content="'|safe ~ common.getinfo("REFRESH", "globalmon", 0) ~ '">'|safe }}
	{% endif %}
	<title>MonitorNjus</title>
	<!-- MonitorNjus -->
	<!-- Copyright (c) {{ common.datum.year }} Steffen Deusch -->
	<!-- https://github.com/SteffenDE/MonitorNjus -->
	<style type="text/css">
	html, body {
		width: 100%;
		height: 100%;
		min-width: 100%;
		min-height: 100%;
	}
	</style>
</head>
<body>
	<iframe src="show{{ '?owndate='|safe ~ owndate if owndate != None else '' }}" style="z-index: 1; position:absolute; height:100%; width:100%; top: 0px; left:0px;" frameborder="0" scrolling="no"></iframe>
	{% for item in common.getwidgets() %}
		{% set typ = common.getwidgTYPfromID(item) %}
		{% if typ == "Logo" and common.getwidgetinfo("Logo", item, "AKTIV") %}
			{% set logovmargin = common.getwidgetinfo("Logo", item, "vmargin") %}
			{% set logomargin = common.addpx(common.getwidgetinfo("Logo", item, "margin")) %}
			{% set logovalign = common.getwidgetinfo("Logo", item, "valign") %}
			{% set logoalign = common.addpx(common.getwidgetinfo("Logo", item, "align")) %}
			{% set logolink = common.getwidgetinfo("Logo", item, "URL") %}
			{% set logowidth = common.addpx(common.getwidgetinfo("Logo", item, "width")) %}
			{% set logoheight = common.addpx(common.getwidgetinfo("Logo", item, "height")) %}
	<div id="logo" style="z-index: 2; {{ logovalign }}:{{ logoalign }};">
		<img align="{{ logovmargin }}" style="{{ 'margin-' ~ logovmargin ~ ':' ~ logomargin }};" width="{{ logowidth }}" height="{{ logoheight }}" src="{{ logolink }}">
	</div>
		{% elif typ == "Freies_Widget" and common.getwidgetinfo("Freies_Widget", item, "AKTIV") %}
			{% set widgetcontent = common.getwidgetinfo("Freies_Widget", item, "URL") %}
			{% set widgetheight = common.addpx(common.getwidgetinfo("Freies_Widget", item, "height")) %}
			{% set widgetwidth = common.addpx(common.getwidgetinfo("Freies_Widget", item, "width")) %}
			{% set widgetvalign = common.getwidgetinfo("Freies_Widget", item, "valign") %}
			{% set widgetalign = common.addpx(common.getwidgetinfo("Freies_Widget", item, "align")) %}
			{% set widgetvmargin = common.getwidgetinfo("Freies_Widget", item, "vmargin") %}
			{% set widgetmargin = common.addpx(common.getwidgetinfo("Freies_Widget", item, "margin"))  %}
	<div id="widget" style="z-index: 2; height:{{ widgetheight }}; width:{{ widgetwidth }}; {{ widgetvalign }}:{{ widgetalign }}; {{ widgetvmargin ~ ':' ~ widgetmargin if widgetvmargin != 'center' else 'position:absolute; left:0; right:0; margin-left:auto; margin-right:auto;' }}">
		{{ widgetcontent|safe }}
	</div>
		{% elif typ == "Adminlink" and common.getwidgetinfo("Adminlink", item, "AKTIV") %}
			{% set adminlinkvmargin = common.getwidgetinfo("Adminlink", item, "vmargin") %}
			{% set adminlinkmargin = common.addpx(common.getwidgetinfo("Adminlink", item, "margin")) %}
			{% set adminlinkvalign = common.getwidgetinfo("Adminlink", item, "valign") %}
			{% set adminlinkalign = common.addpx(common.getwidgetinfo("Adminlink", item, "align")) %}
	<div id="admin_link" style="z-index: 3; position: fixed; background:none; {{ adminlinkvalign }}:{{ adminlinkalign }}; {{ adminlinkvmargin ~ ':' ~ adminlinkmargin if adminlinkvmargin != 'center' }}">
		<small style=float:{{ adminlinkvmargin }};>{{ common.datum.strftime("%d.%m.%Y %H:%M:%S") }}</small><br>
		<a style="text-decoration: none;" href="{{ url_for("backend.admin_index") }}">monitor<b>njus</b>{{ common.version|safe }} </a>&copy; Steffen Deusch
	</div>
		{% endif %}
	{% endfor %}
	{% if settings.triggerrefresh and trigger|int != 1 %}
	<script>
	setTimeout(function() {
		if(typeof(EventSource) !== "undefined") {
			var source = new EventSource("triggerrefresh");
			source.onmessage = function(event) {
				if (event.data == "reload") {
					var meta = document.createElement('meta');
					meta.httpEquiv = "refresh";
					meta.content = "2";
					document.getElementsByTagName('head')[0].appendChild(meta);
				}
			};
		}
	}, 3000);
	</script>
	{% endif %}
</body>
</html>

templates/frontend/show.html
<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	<link href="{{ url_for('static', filename='css/materialize.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
	{% if common.getinfo("REFRESHAKTIV", "global", 0) == 1 %}
	<meta http-equiv="refresh" content="{{ common.getinfo("REFRESH", "global", 0) }}">
	{% endif %}
	<title>MonitorNjus</title>
	<!-- MonitorNjus -->
	<!-- Copyright (c) {{ common.datum.year }} Steffen Deusch -->
	<!-- https://github.com/SteffenDE/MonitorNjus -->
</head>
{% if geteilt %}
<frameset frameborder="0" rows="*,0">
	<frameset frameborder="0" cols={{ teilung|int }},{{ 100-teilung|int }}>
		<frame scrolling="no" src="contentset?seite=1{{ '&owndate='|safe ~ owndate if owndate != None else '' }}" name="links" />
		<frame scrolling="no" src="contentset?seite=2{{ '&owndate='|safe ~ owndate if owndate != None else '' }}" name="rechts" />
	</frameset> 
</frameset>
{% elif (linksgeteilt and not rechtsgeteilt and timeL) or (linksgeteilt and rechtsgeteilt and timeL and not timeR) %}
<frameset frameborder="0" rows="*,0">
	<frame scrolling="no" src="contentset?seite=1{{ '&owndate='|safe ~ owndate if owndate != None else '' }}" name="links" />
</frameset>
{% elif (rechtsgeteilt and not linksgeteilt and timeR) or (rechtsgeteilt and linksgeteilt and timeR and not timeL) %}
<frameset frameborder="0" rows="*,0">
	<frame scrolling="no" src="contentset?seite=2{{ '&owndate='|safe ~ owndate if owndate != None else '' }}" name="rechts" />
</frameset>
{% else %}
{{ raise_helper("Warning('<h3>Warnung:</h3><h4>Keine Seite aktiv!</h4>')") }}
{% endif %}
</html>

templates/frontend/show_iframe.html
<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
	<link href="{{ url_for('static', filename='css/materialize.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
	{% if common.getinfo("REFRESHAKTIV", "global", 0) == 1 %}
	<meta http-equiv="refresh" content="{{ common.getinfo("REFRESH", "global", 0) }}">
	{% endif %}
	<title>MonitorNjus</title>
	<!-- MonitorNjus -->
	<!-- Copyright (c) {{ common.datum.year }} Steffen Deusch -->
	<!-- https://github.com/SteffenDE/MonitorNjus -->
	<style>
		html, body, iframe { height: 100%; }
	</style>
</head>
<body>
{% if geteilt %}
	<iframe scrolling="no" frameborder="0" src="contentset?seite=1" name="links" style="float: left; position:static; width: {{ teilung|int }}%;" ></iframe>
	<iframe scrolling="no" frameborder="0" src="contentset?seite=2" name="rechts" style="float: right; position:static; width: {{ 100-teilung|int }}%;" ></iframe>
{% elif (linksgeteilt and not rechtsgeteilt and timeL) or (linksgeteilt and rechtsgeteilt and timeL and not timeR) %}
	<iframe scrolling="no" frameborder="0" src="contentset?seite=1" name="links" style="position:static; width: 100%;" ></iframe>
{% elif (rechtsgeteilt and not linksgeteilt and timeR) or (rechtsgeteilt and linksgeteilt and timeR and not timeL) %}
	<iframe scrolling="no" frameborder="0" src="contentset?seite=2" name="rechts" style="position:static; width: 100%;" ></iframe>
{% else %}
{{ raise_helper("Warning('<h3>Warnung:</h3><h4>Keine Seite aktiv!</h4>')") }}
{% endif %}
</body>
</html>